version: '3.8'
services:
  api.service:
    build: .
    restart: always
    ports:
      - "5080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    
  postgres:
    image: postgres:latest
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 22010047
      POSTGRES_DB: LibDB
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
 